server:
  port: 80
spring:
  application:
    name: consumer-service
logging:
  level:
    com.jf.springcloud.consumer: info
services:
  service_name: provider-service

eureka:
  instance:
    lease-renewal-interval-in-seconds: 1    #周期通知存活时间
    lease-expiration-duration-in-seconds: 2 #告诉后端自己过多久不回复就可以被当作过期删除
    instance-id: consumer
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://www.eureka01.com:8761/eureka/,http://www.eureka02.com:8762/eureka/

info:
  name: consumer