server:
  port: 80
spring:
  application:
    name: consumer-service
logging:
  level:
    com.jf.springcloud.consumer: info
services:
  service_name: provider-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://www.eureka01.com:8761/eureka/,http://www.eureka02.com:8762/eureka/
