server:
  port: 8801
spring:
  application:
    name: provider-service

eureka:
  instance:
    lease-renewal-interval-in-seconds: 1    #周期通知存活时间
    lease-expiration-duration-in-seconds: 2 #告诉后端自己过多久不回复就可以被当作过期删除
  #    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
