server:
  port: 8801
spring:
  application:
    name: provider-service

eureka:
#  instance:
#    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
