server:
  port: 8802
spring:
  application:
    name: provider-service

eureka:
#  instance:
#    hostname: www.jf.provider02
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
