server:
  port: 8802
spring:
  application:
    name: provider-service

eureka:
  instance:
    lease-renewal-interval-in-seconds: 1    #周期通知存活时间
    lease-expiration-duration-in-seconds: 2 #告诉后端自己过多久不回复就可以被当作过期删除
    instance-id: provider-8002
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      zone1: http://www.eureka01.com:8761/eureka/
      zone2: http://www.eureka02.com:8762/eureka/
